[profile.default]
solc_version = "0.8.25"
src = "src"
out = "out"
via_ir = true
libs = ["lib"]
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "@openzeppelin-foundry-upgrades/=lib/openzeppelin-foundry-upgrades/",
    "@eigenlayer/=lib/eigenlayer-contracts/",
  "@eigenlayer-middleware/=lib/eigenlayer-middleware/",
  "forge-std/=lib/forge-std/src/"
  ]